SOURCE_FILE_PATH = 'source.xlsx'
SOURCE_SHEET_NAME = 'FEB20'
MAIN_EXCEL_FILE_NAME = 'main2.xlsx'
MAIN_SHEET_NAME = 'FEB20'
NORIDIAN_USERNAME = ''
NORIDIAN_PASSWORD = ''

CONSOLIDATE_SOURCE_SHEET_NAME = 'FEB20'
CONSOLIDATE_MAIN_SHEET_NAME = 'FEB20'
CONSOLIDATE_SHEET_NAME = 'FEB20_test'
CONSOLIDATE_FILE_NAME = 'consolidated.xlsx'

SOURCE_CLEAN_FILE_NAME = 'source_clean.xlsx'
SOURCE_CLEAN_SHEET_NAME = 'JUN20'